### ISSUE TITLE
Change repository name to "future-web"

### ISSUE THREAD

**Issue by filipenevola** [CodeFTW/future-web#30]
I think we should rename our repository because it is now targeting what is the best for web development.

The current name just reflect part of that.

What do you think? @JesseCarlos @tgmarinho @denihs @semateos

**Comment by denihs** [comment]
I think that it's a good idea!

**Comment by tgmarinho** [comment]
Nice, good idea!

**Comment by filipenevola** [comment]
Done! Update your local repositories. The easiest way is to start something new.
