### ISSUE TITLE
When I run the meteor npm instart I receive the error MongoError: $set is empty

### ISSUE THREAD

**Issue by tgmarinho** [CodeFTW/future-web#59]
Console error:

MongoError: '$set' is empty. You must specify a field like so: {$set: {<field>: ...}}
W20180316-11:22:05.218(-4)? (STDERR)     at Function.MongoError.create (/home/tgmarinho/.meteor/packages/npm-mongo/.2.2.34.6z9stb.xt86g++os+web.browser+web.cordova/npm/node_modules/mongodb-core/lib/error.js:31:11)
W20180316-11:22:05.219(-4)? (STDERR)     at toError (/home/tgmarinho/.meteor/packages/npm-mongo/.2.2.34.6z9stb.xt86g++os+web.browser+web.cordova/npm/node_modules/mongodb/lib/utils.js:139:22)

code where I have detected the error:
`Accounts.loginServiceConfiguration.upsert(
    {
      service: 'facebook',
    },
    {
      $set: {
        appId: Meteor.settings.public.FACEBOOK_APP_ID,

        secret: Meteor.settings.FACEBOOK_SECRET_KEY,
      },
    }
  );
});
`

Solution is execute $`meteor --settings private/env/dev/settings.json` for load the props every time...

There way for execute once time `meteor --settings private/env/dev/settings.json` and another times just `meteor run`  ?

I think we need document it on the README.md

**Comment by JesseCarlos** [comment]
Just execute `npm start` and don't `meteor npm start,` the script `npm start` make this for you, look the file "examples/todo/package.json"

**Comment by tgmarinho** [comment]
Thank you @JesseCarlos you are right! =) Thats works for me!
